apiVersion: apps/v1
kind: Deployment
metadata:
  name: iemdb-back-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iemdb-backend
  template:
    metadata:
      labels:
        app: iemdb-backend
    spec:
      containers:
        - name: iemdb-backend
          image: ffmohammad/iemdb:back-end-1.0
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-config
                  key: db-url
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  name: iemdb-back-service
spec:
  type: NodePort
  selector:
    app: iemdb-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30433
